name: Flutter CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Install dependencies
      run: |
        cd frontend
        flutter pub get

    - name: Run code formatting check
      run: |
        cd frontend
        dart format --output=none --set-exit-if-changed .

    - name: Run static analysis
      run: |
        cd frontend
        flutter analyze

    - name: Run tests
      run: |
        cd frontend
        flutter test
